proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: mingchu
    password: password
    groups: admins
  - name: sean
    password: password
  docker:
      internal-networking: true
  specs:
  - id: test
    display-name: Test App
    description: This is a test application.
    container-cmd: []
    container-volumes: ["/Users/mxu3/Documents/projects:/folder"]
    container-image: shiny_test:latest
    container-network: sp-mda-net
  - id: mda_gde
    display-name: Genomic Data Explorer
    container-cmd: []
    container-image: xmc811/shiny_gde_run:1.0
    container-network: sp-mda-net

logging:
  file:
    shinyproxy.log
